### ISSUE TITLE
Fix abbr styling

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/t3SphinxThemeRtd#101]
PR on the way

**Comment by josefglatz** [comment]
Until #102 is fixed it's not possible to fix this.

My proposed code snippet for this issue is

```patch
Index: sass/_t3_addons.sass
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sass/_t3_addons.sass	(revision c1ed98e37cd6c73a1ebf9052ce36b4444c03e258)
+++ sass/_t3_addons.sass	(date 1550039379000)
@@ -30,6 +30,9 @@
   padding: 6px 10px
   border-radius: 15px
 
+abbr[title]
+  text-decoration: none
+
 input
   &[type="text"]
     font-size: 100%

```

This fixes the double dotted line under an `abbr` tag in a rendered TYPO3 documentation

**Comment by josefglatz** [comment]
principially tested locally with new feature branch of t3docs/render-documentation repo. I will push the PR if the upstream is ready

**Comment by marble** [comment]
Resolve with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/commit/44e58e9825ba0ab26dfc0b1d4fdf8c765418ac29

![grafik](https://user-images.githubusercontent.com/307057/67719371-0262f980-f9d2-11e9-8d3e-ea624a9882e1.png)
