### ISSUE TITLE
development environment can't be setup due missing bower dependency

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/t3SphinxThemeRtd#102]
```
>> bower font-source-sans-pro-sass#~2.10.0          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/Arelav/font-source-sans-pro.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/Arelav/font-source-sans-pro.git/' not found
>> Additional error details:
>> remote: Repository not found.
>> fatal: repository 'https://github.com/Arelav/font-source-sans-pro.git/' not found
>> Exited with code: 1.
```

**Comment by DanielSiepmann** [comment]
Please have a look at https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/tree/feature/cleanup-frontend-stack and follow https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/tree/feature/cleanup-frontend-stack#set-up-a-development-environment

Note that sphinx is optional, ruby and sass via ruby is required.

Does that help?

**Comment by josefglatz** [comment]
It's fixed in the feature branch. So I close this issue
