### ISSUE TITLE
Improve readability by adding more space around images

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#104]
If you compare docs.typo3.org with other sources, the docs.typo3.org are not very well readable. This has a number of reasons, one of them is how images are displayed. 

Suggestion (not all should be implemted!): 

* indent images
* add more whitespace around images, so that the images and text don't all blend together
* make the shadow around the images bigger. Our shadow (with-shadow) is very unobtrusive
* add whitespace between caption under image and image

This is an example of how images can be displayed on a page: https://developers.google.com/web/tools/chrome-devtools/speed/get-started#report

![image-example](https://user-images.githubusercontent.com/13206455/53558318-122af500-3b48-11e9-8524-617c1b86519c.png)

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
