### ISSUE TITLE
Add piwik tracker to themes

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/t3SphinxThemeRtd#105]
moved from GmbH Jira:
The piwik tracker needs to be properly added to all online themes.
Offline Themes need to register the tracker with the full URL (including the domain)

I don't know if this is still needed, maybe @DanielSiepmann has more info?

**Comment by marble** [comment]
This ticket should be obsolete. It was created at a time when the tracker code was - erroneously - added to offline manuals as well. This isn't the case any more.
