### ISSUE TITLE
Color scheme (orange) of docs.typo3.org inconsistent with TYPO3 style guide

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#110]
**Summary**: 

* https://docs.typo3.org, https://typo3.com and some logos use "dark" TYPO3 orange: #ff8700
* ![#ff8700](https://placehold.it/15/ff8700/000000?text=+) `#ff8700`

* https://typo3.org and [styleguide](https://typo3.org/fileadmin/t3o_common_storage/images/styleguide/TYPO3_Printstyleguide_2018-02-23.pdf) use "lighter" TYPO3 orange: #f49700
- ![#f49700](https://placehold.it/15/f49700/000000?text=+) `#f49700`

AFAIK the lighter one (from styleguide) should be used everywhere, so we should change this.

(I have not checked other colors, only orange)

---------

I created new images from some of the [icons that was prepared by the design team](https://github.com/TYPO3-Documentation/images/blob/master/design-team/icons_preview/Images.rst) and noticed that the "TYPO3" orange shades from the style guide clash with the orange we use on docs.typo3.org for "Edit me on GitHub", "Area for home in top left" and  the "orange buttons".

These use the color rgb(255, 135, 0), #ff8700.

The orange colors from [Style Guide](https://typo3.org/fileadmin/t3o_common_storage/images/styleguide/TYPO3_Printstyleguide_2018-02-23.pdf) are:

```
key color
CMYK: 0/47/100/0
RGB: 244/151/0
Hex: f49700

stage orange dark
CMYK: 0/47/100/10
RGB: 225/141/0
Hex: e18d00

stage orange light
CMYK: 0/40/85/0
RGB: 247/168/49
Hex: f7a831
```

The icons from the design team (e.g. arrow) use the key color. 

This is how it looks: 

https://docs.typo3.org/Tips/UsingThisSite/Index.html

![mobilemenu](https://user-images.githubusercontent.com/13206455/54752610-0f6b6f00-4bdf-11e9-979a-147e67443a99.png)

**Comment by sypets** [comment]
![colors](https://user-images.githubusercontent.com/13206455/54976394-836c9500-4f9a-11e9-9fb1-b4185ca9efed.png)

**Comment by sypets** [comment]
This is blocking the updating of manuals and replacement of images until sample image icons can be agreed upon: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/61

**Comment by sypets** [comment]
---------
TYPO3
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/backend/Resources/Public/Images/typo3_logo_orange.svg
#ff8700

typo3.com
https://typo3.com/typo3conf/ext/template_typo3com/Resources/Public/Images/logo.svg
#ff8700

docs.typo3.org (see top left)
#ff8700

-------

typo3.org: logo
https://typo3.org/typo3conf/ext/t3olayout/Resources/Public/Images/Template/typo3_nomargins.svg
#f49800

---------

Styleguide Assets
https://typo3.org/fileadmin/t3o_common_storage/images/styleguide/Assets.zip
Logos/TYPO3/typo3.svg
#f49700

Color listed in Style Guide
https://typo3.org/fileadmin/t3o_common_storage/images/styleguide/TYPO3_Printstyleguide_2018-02-23.pdf
#f49700

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140

**Comment by sypets** [comment]
@benjaminkott If you add a 

`Resolves: <issue number> `

to your commit message, the corresponding issue will get closed automatically. Might make the workflow a little easier. 

The usage is the same as for core patches. 

If you don't want the issue to get closed, you can use "Related" instead of "Resolves"
