### ISSUE TITLE
Make contrast of captions in menu stronger

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#117]
Update: caption are already being used in

* [Writing Documentation](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/)
* Contribution Guide

---

If you use :caption: in :toctree: menu captions are created. These can be used as dividers to group several similar top level menu items without creating another menu layer on top.

I find this very useful and would like to use this. But, the contrast is very low. It would be great, if a brighter color was used.

e.g. 
![menu](https://user-images.githubusercontent.com/13206455/59042982-b75a1580-887b-11e9-9d48-43091bdf2d96.png)

## With blue

we have a blue in [styleguide](https://typo3.org/fileadmin/t3o_common_storage/images/styleguide/TYPO3_Printstyleguide_2018-02-23.pdf): #538bb3

this would look like this:

![menu_captions_blue](https://user-images.githubusercontent.com/13206455/61304433-742f8280-a7e9-11e9-8867-68ebdbd2d1f7.png)

## Readthedocs: 

readthedocs also uses a blue for captions.

![rtd](https://user-images.githubusercontent.com/13206455/59043087-e5d7f080-887b-11e9-9299-79046032bdc1.png)

https://docs.readthedocs.io/en/stable/index.html

## Related:

* https://github.com/TYPO3-Documentation/T3DocTeam/issues/87

**Comment by marble** [comment]
Is fixed in the next, upcoming version
![grafik](https://user-images.githubusercontent.com/307057/67617748-a6884d00-f7e6-11e9-87ea-1a69b6a8d36a.png)
