### ISSUE TITLE
Release version is not displayed on mobile

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#118]
On desktop, the release version is displayed next to the title. On mobile, it is not:

![mobile-top](https://user-images.githubusercontent.com/13206455/59551376-e60d7580-8f78-11e9-8849-ee966c07e993.png)

So, on mobile you can't see right away which version you are reading. You have to open the menu.

Related: 

* #93 
* #82

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
