### ISSUE TITLE
The caption for figure could use a little more distance to the image

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#121]
![figure-caption](https://user-images.githubusercontent.com/13206455/60757445-ebeff700-a00a-11e9-9a4e-1b4d734be3c2.png)

https://docs.typo3.org/m/typo3/guide-example-extension-manual/master/en-us/Editor/Index.html

**Comment by sypets** [comment]
This is how it might look (uses a stronger drop shadow too as suggested in #104, #98 and #114.

![figure-caption2](https://user-images.githubusercontent.com/13206455/60757464-50ab5180-a00b-11e9-8d38-b8ee829d9e2b.png)

**Comment by sypets** [comment]
@marble I think we can close this now. Looks ok:

![caption](https://user-images.githubusercontent.com/13206455/70771289-d4165f00-1d70-11ea-9a0a-a1d51c0f52fb.png)
https://docs.typo3.org/m/typo3/demo-t3SphinxThemeRtd/master/en-us/ImagesAndFigures/Index.html

**Comment by marble** [comment]
Great!
