### ISSUE TITLE
Contrast for some syntax highlighting colors - readability could be improved

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#122]
I don't know if this is something that is easily changable (like changing color palette for syntax highlighting). Some code snippets well readable, some not. Depends on what is used.

## Example for things not well readable:

* text with backticks (e.g. textroles or external links) in reST

![rest](https://user-images.githubusercontent.com/13206455/61285126-a24c9c80-a7c0-11e9-9f8d-e26111b8e2f0.png)

https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CheatSheet.html

![code](https://user-images.githubusercontent.com/13206455/61288251-05d9c880-a7c7-11e9-92f5-292e0099622e.png)

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Database/QueryBuilder/Index.html

## Examples outside of TYPO3

Compare, for example, with usetypo3 where the contrast is stronger for some colors (text brighter):

![rest2](https://user-images.githubusercontent.com/13206455/61285244-dc1da300-a7c0-11e9-9e39-90796e5812cb.png)

https://usetypo3.com/did-you-know.html

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
