### ISSUE TITLE
Task return value

### ISSUE THREAD

**Issue by Mordef** [TYPO3-Documentation/t3SphinxThemeRtd#126]
https://docs.typo3.org/c/typo3/cms-scheduler/master/en-us/DevelopersGuide/CreatingTasks/Index.html

Please extend the function public function execute()
It must return "true" on success, otherwise the backend will allways say that the execution failed.

**Comment by sypets** [comment]
@Mordef You can directly make the change on the [documentation page](https://docs.typo3.org/c/typo3/cms-scheduler/master/en-us/DevelopersGuide/CreatingTasks/Index.html) by clicking on "Edit me on GitHub" on the top right. 

The community is welcome to directly participate in improving the documentation.

For more information see, https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/GithubMethod.html
