### ISSUE TITLE
403 Error on docs.typo3.org for my documentation

### ISSUE THREAD

**Issue by featdd** [TYPO3-Documentation/t3SphinxThemeRtd#127]
Hi,

the link in the [extension browser](https://extensions.typo3.org/extension/dpn_glossary/) to my documentation results in a 403 (https://docs.typo3.org/typo3cms/extensions/dpn_glossary/stable/)

There hasn't been any changes in the last releases, is this the right place for this issue?

Greetings
Daniel

**Comment by sypets** [comment]
You can report problems with documentation rendering either 

* on Slack (https://typo3.slack.com) in #typo3-documentation (see https://typo3.org/community/teams/documentation/#c9886)
* or in this issue: https://github.com/TYPO3-Documentation/T3DocTeam/issues/92 (this is also linked on the ["Migrate Documentation"](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html) page under step 4: request redirects)

This here is not the correct repository, but it's not a problem. I will forward your request.

In any case, you should request a redirect if you have not done so already. I saw that your extension has already been rendered with the new mechanism: https://docs.typo3.org/p/featdd/dpn-glossary/3.0/en-us/

Actually, extensions.typo3.org should automatically update its information and use the new URL. This may take up to a day.

**Comment by featdd** [comment]
Hi @sypets,

thanks for all the information and the forwaring of my request.

Greetings
Daniel
