### ISSUE TITLE
Indent the list of subtopics in 'genindextable'

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/t3SphinxThemeRtd#132]
The following indent is needed:
![grafik](https://user-images.githubusercontent.com/307057/67683925-8ac1aa00-f992-11e9-8a38-0e654cb225bf.png)

**Comment by marble** [comment]
Solved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/commit/8554bace4989929b512bcb01b5d94e2c78bc0f7a

**Comment by sypets** [comment]
:thumbsup:

See also PR using index in contrib guide: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/151
