### ISSUE TITLE
Position "Related links" correctly

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/t3SphinxThemeRtd#133]
With the recent larger merge the html of "Related links" has moved. In CSS there is a position:absolute, which leads to this display now:
![grafik](https://user-images.githubusercontent.com/307057/67694581-db8dce80-f9a3-11e9-94e8-9cdce4209255.png)

**It may be necessary to rethink positioning!**

To fix the - clearly wrong - display, I've changed it to position:fixed.
With this - interesting! - result:

![grafik](https://user-images.githubusercontent.com/307057/67694762-2f001c80-f9a4-11e9-963c-f1ec5e0c98f7.png)

**Comment by marble** [comment]
Please have a look at the online docs now. Benjamin, is this what you wanted to achieve by moving the "related files div"?

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
