### ISSUE TITLE
f:switch code example broken

### ISSUE THREAD

**Issue by npoggenburg** [TYPO3-Documentation/t3SphinxThemeRtd#139]
https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Switch.html
![Bildschirmfoto 2019-12-03 um 11 27 36](https://user-images.githubusercontent.com/18659807/70042951-0d580d80-15c0-11ea-8814-f7463c8e8346.png)

**Comment by sypets** [comment]
This is not a problem of the theme. It is a problem of the automatic rendering tool chain for Fluid ViewHelpers. Please see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper/blob/master/Documentation/Index.rst

The [Fluid ViewHelper References](https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/Index.html) are automatically generated from source code comments in [Fluid](https://github.com/TYPO3/Fluid) and TYPO3 Core. The comments in Fluid used a syntax based on Markdown, while the comments in the TYPO3 core have been converted to reStructruedText. The rendering toolchain (for the ViewHelpers) can currently only handle reStruturedText. That is why part of the ViewHelper Reference (specifically the part from standalone fluid) currently look broken.

We cannot easily solve this rendering problem currently (at least not right away).
