### ISSUE TITLE
6.2 LTS concatenateCss description must be extended

### ISSUE THREAD

**Issue by PfefferT** [TYPO3-Documentation/t3SphinxThemeRtd#14]
Depending on the concatenateCss documenation of 6.2LTS I thought it would be possible to concatenate all my css files depending on its media attribute, but later I found this issue: https://forge.typo3.org/issues/33137, which said that only media type all and none are really concatenated and nothing more. The fix of it was in TYPO3 7.x . So the description of the 6.2LTS concatenateCss must define that only media type all and css files without media attribute are concatenated.

**Comment by marble** [comment]
The place here is about the development of the THEME that we're now using to render TYPO3 documentation. The issue you're mentioning is about the TYPO3 documentation. Probably you're talking of https://docs.typo3.org/typo3cms/TyposcriptReference/6.2/Setup/Config/Index.html#concatenatecss !?

Can you provide a sentence as a proposal there ("Edit me on Github") or in the issue tracker? https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/issues

Thank you.
