### ISSUE TITLE
Next  / prev page causes new page to "jump" while rendered

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#141]
When paging in ["TYPO3 Explained" : "Api Overview"](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Index.html)  (e.g. ALT-n) longer pages seem to "jump up and down" while being rendered (footer appears and disappears). 

This also happens in areas which do not have excessively long menus, e.g. ["TYPO3 Explained: Extension Development"](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/Index.html)

----

This happens in current theme and next generation theme #140.

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
