### ISSUE TITLE
Error - Not called from a command line interface (e.g. a shell or scheduler).

### ISSUE THREAD

**Issue by kledo-34** [TYPO3-Documentation/t3SphinxThemeRtd#148]
Hey there,
I'm sure this is not an issue on your side, but I don't know where else to ask for a solution at the moment.
When I try to run the scheduler via Cron Job or just from the command line (my hosting company is strato.de, command line ssh session with PuTTy) I always get the answer 
`"Not called from a command line interface (e.g. a shell or scheduler)."`
I'm not a pro in command line so what does that mean. My Command is this: 
`/bin/php /myRootPathFromTypo3Backend/typo3/sysext/core/bin/typo3 scheduler:run`
The root path is correct, otherwise I would get an error command not found.
I also tried this here (https://blog.mobasoft.de/typo3/typo3-scheduler-cronjob-bei-strato/) executing a php file from the command line which should then execute the scheduler, but same result.
So can you help me out with this to make things work? I would be really happy.
Thanks a lot in advance.

**Comment by kledo-34** [comment]
Update: 
I can see, that my PHP_SAPI Value is cgi-fcgi istead of the expected cli, but how can I change that?

**Comment by kledo-34** [comment]
Can I delete an issue completely, this was the wrong repository, this here is not the typo3 scheduler, went with the wrong link in the typo3 documentation, sorry.

**Comment by sypets** [comment]
No problem. Report core issues on forge: https://forge.typo3.org/projects/typo3cms-core/issues
