### ISSUE TITLE
Example "Setting fallbacks for og:image and twitter:image" gives no absolute image path

### ISSUE THREAD

**Issue by fischhase** [TYPO3-Documentation/t3SphinxThemeRtd#149]
Dear documentation editor,

thanks for your example "Setting fallbacks for og:image and twitter:image". It is exactly the solution for my problem, but this example does not work. IMG_RESOURCE returns the image path widthout baseurl. OpenGraph needs an absolute path incl. protocoll and domain. It would be nice, if the example would work correctly.

Thank you 
Martin

**Comment by sypets** [comment]
@fischhase Please add the URL to the documentation page where you found the example.

**Comment by fischhase** [comment]
Hallo Sybille,
sorry, I thought it was mentioned when I click on "Report issue". The documentation page is https://docs.typo3.org/c/typo3/cms-seo/master/en-us/Configuration/Index.html
Bye
Martin

**Comment by sypets** [comment]
@fischhase Ok, this is in the SEO system extension documentation. That would be handled in the core. I created an issue on forge for you: https://forge.typo3.org/issues/90830

I also noticed that the seo documentation is rendered with the old theme. It looks different (e.g. menu in left panel with dark background) We recently updated our theme. It should now look different. See start page: https://docs.typo3.org. I will trigger rerendering if possible.

What you probably did is click on the link on the bottom "Report theme issues here"

So you got directed to this repository. But this repository is for the theme, not for the documentation itself.

What you can do in the future to get to the issues for the manual you are reading:

Click on _Issues_ at the bottom. 

![issues](https://user-images.githubusercontent.com/13206455/77540286-163c5a00-6ea3-11ea-8d85-cc89987e788e.png)


You will get directed to the issues for the repository of the manual you are reading. For the core system extensions, that would be 

See for example systext: form documentation: https://docs.typo3.org/c/typo3/cms-form/master/en-us/

If you click on "Issues" at the bottom, you are directed to forge: https://forge.typo3.org/projects/typo3cms-core/issues 

There you can create an issue. Use category ~"documentation"~ "seo" for seo extension. 

----

Even better, if you can make the change yourself, do it. Click on "Edit on GitHub" on the top right of the page where you found the error. 

![editgithub](https://user-images.githubusercontent.com/13206455/77540336-2fdda180-6ea3-11ea-8379-e538de13f265.png)


---

I personally find it unfortunate that documentation and core is fragmented this way with different issue trackers and workflows. This may be changed in the future, but currently there is not much we can do.

----

I am closing this issue.
