### ISSUE TITLE
"+" plus icon in menu not really visible

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3SphinxThemeRtd#15]
The plus icon in the menu is not really visible - I had this at https://docs.typo3.org/typo3cms/TCAReference/Index.html and did not see that I could expand the submenus.

The color of the plus icon should be brighter, so that I can see that there is something to click.

![2016-01-04 typo3 docs plus icons](https://cloud.githubusercontent.com/assets/59036/12089582/9d4fdf4e-b2e6-11e5-9331-fb3d443f5bff.png)

**Comment by marble** [comment]
You're right, indeed! Thanks for reporting! I'll fix that.

**Comment by marble** [comment]
Fixed in https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/commit/dbf0b3eee7f4a8e4471b3038dd3f08e74f3959b4
