### ISSUE TITLE
Link the 'genindex.html' page!

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/t3SphinxThemeRtd#19]
With the new theme a proper index page is generated. But in our theme we don't have a link to it. Fix that!

For example, there IS a page https://docs.typo3.org/typo3cms/extensions/core/genindex.html

It's empty right now, because nobody has been writing index entries up to now in the reST source. If somebody does the page will be filled. But it needs to be linked. An example of using indexes can be found here:
https://docs.typo3.org/typo3cms/extensions/sphinx/genindex.html

**Comment by xperseguers** [comment]
Hi. Actually it's slightly wrong, I reported the problem for the general index about 2 years ago : https://forge.typo3.org/issues/48857 :D

**Comment by marble** [comment]
With the new theme t3SphinxThemeRtd Forge issue #48857 is solved.

**Comment by marble** [comment]
The index page is always generated with the new theme. It can be easily linked in the menu like so:<pre>
.. toctree::

   Index of Tags   <https://docs.typo3.org/typo3cms/Snippets/genindex.html>
   Sitemap
   2017/Index
</pre>

I take that as a good enough  solution for now.
