### ISSUE TITLE
// code

### ISSUE THREAD

**Issue by woepwoep** [TYPO3-Documentation/t3SphinxThemeRtd#20]
Why is // code ?
TDD has no real code. Why is there no example code?https://docs.typo3.org/typo3cms/ExtbaseFluidBook/2-BasicPrinciples/4-Test-Driven-Development.html
thx, Ron

**Comment by marble** [comment]
Hi Ron, please note that this repository is about the THEME we are using to render manuals. You are addressing the "ExtbaseFluidBook", so you would like to go to:
![035](https://cloud.githubusercontent.com/assets/307057/12986746/37b85270-d0f9-11e5-8921-46047b76f5ec.png)

Many people once sat down, took the german book and created an english transcription. Voluntarily, not being paid, but enthusiastic. It seems they left out the example code. Are you the one to fill it in?

You know, everybody can do that. Note the "Edit me on Github" button!
![036](https://cloud.githubusercontent.com/assets/307057/12986915/f7188770-d0f9-11e5-8b7d-d7b259aedd14.png)
