### ISSUE TITLE
Code blocks are not displayed in the documentation

### ISSUE THREAD

**Issue by forethoughtde** [TYPO3-Documentation/t3SphinxThemeRtd#21]
Code blocks are not displayed in the extBase documentation. Instead showing, <remark>TODO: Enter Code</remark>

Refererence: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/2-BasicPrinciples/1-Object-oriented%20Programming-in-PHP.html#interfaces

**Comment by marble** [comment]
Actually this has nothing to do with the theme. Instead it's about missing content in the manual. So I close this ticket here.
