### ISSUE TITLE
SecurityGuide: Wrong example for backend user's TSconfig field "option.lockToIP"

### ISSUE THREAD

**Issue by jdkpix** [TYPO3-Documentation/t3SphinxThemeRtd#24]
Please change the configuration example to "options.lockToIP".
https://docs.typo3.org/typo3cms/SecurityGuide/GuidelinesIntegrators/GlobalTypo3Options/Index.html#enabledbeuseriplock

**Comment by marble** [comment]
Done. Thanks.
