### ISSUE TITLE
A few subparts configuration in templating tutorial not working in cms 7.6

### ISSUE THREAD

**Issue by Chhunlong** [TYPO3-Documentation/t3SphinxThemeRtd#25]
When i try to follow how to configure subparts of TOPNAV and SUBNAV it is not render to the frontend. but in case i used special properties it will render. please help

**Comment by marble** [comment]
Issues of this repository are about the LAYOUT (theme) of the TYPO3 documentation. Please find the help you are looking for at https://forum.typo3.org/

**Comment by Chrissitopher** [comment]
This obviously is related to the TemplatingTutorial. From the two sentences in this issue it is unclear, what the problem might be and whether this might be a bug in the documentation.

Please ask in a forum at https://forum.typo3.org/!

In case this is a bug in the document, feel free to open an issue at https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-Templating

**Comment by Chhunlong** [comment]
@marble @Chrissitopher Thanks for your both comments. I'll report to the forum
