### ISSUE TITLE
Higlighted items have a low contrast

### ISSUE THREAD

**Issue by jvanderkroon** [TYPO3-Documentation/t3SphinxThemeRtd#26]
The background color of a highlighted element (after a search) is #ffc800 and the text color is #E0E0E0 in PRE elements.

It is goog readable when you make the text color black 

.rst-content .highlighted {
    color: black;
}

**Comment by marble** [comment]
Do you have a link at hand?

**Comment by jvanderkroon** [comment]
https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/DataTypes/Gettext/Index.html?highlight=pagelayout#pagelayout

![image](https://cloud.githubusercontent.com/assets/3327836/17268573/18b062a4-562e-11e6-8107-136e40fb4e85.png)

**Comment by marble** [comment]
Great, thank you for the screenshot. A change will now be rolled out with the next release:
![image](https://cloud.githubusercontent.com/assets/307057/18413240/64b47f9c-77a2-11e6-93a9-1f8920bbf457.png)
