### ISSUE TITLE
Links are not very visible

### ISSUE THREAD

**Issue by fsuter** [TYPO3-Documentation/t3SphinxThemeRtd#27]
Hyperlinks are currently brown, which makes them difficult to distinguish from the black main text. A different colour could be chosen, like the TYPO3 orange for example. Another possibility could be to keep the existing colour but restore the underlining.

**Comment by marble** [comment]
Some manuals are shown with this (experimental) CSS. Is this working better for you? https://docs.typo3.org/typo3cms/CoreApiReference/ Link color has more contrast, is more "aggressive".
