### ISSUE TITLE
Tuturials are currently shown in French

### ISSUE THREAD

**Issue by dkd-dobberkau** [TYPO3-Documentation/t3SphinxThemeRtd#28]
If i go to https://docs.typo3.org/typo3cms/Tutorials/Index.html and click in the Getting Started Tutorial Link I will get the Tutorial in French:

https://docs.typo3.org/typo3cms/GettingStartedTutorial/Localization/fr_FR/Index.html#start

Can you change this to English?

**Comment by marble** [comment]
Hi Olivier, note that this repo is about theme (=layout) issues, but nevertheless you reached the right person. I'm heavily working on migration to a new buildchain for documentation. It will fix that problem. Beginning of next week, I hope. The old cronjob renders French last and leaves those links for "interlinking" between manuals. So I guess I won't waste time on fixing the old tool. Have a nice T3DD!
