### ISSUE TITLE
Enable highlighting for inline code

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/t3SphinxThemeRtd#29]
Yes, it is possible!

See: 
- !!! https://groups.google.com/forum/#!searchin/sphinx-users/highlight%7Csort:relevance/sphinx-users/-4Waaw9qQx4/jnXBjKuQKFMJ
- http://stackoverflow.com/questions/10870719/inline-code-highlighting-in-restructuredtext
- http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-markup

**Comment by sypets** [comment]
Isn't this already implemented?

**Comment by marble** [comment]
This is not about code-blocks, but about *inline' code. Probably it's not a good idea anyway to go for that.

**Comment by sypets** [comment]
I would say that the current possibilities are quite sufficient.

**Comment by marble** [comment]
Considered but rejected. Wouldn't achieve much - if anything, could be distracting, trying to implement this led to troubles.
