### ISSUE TITLE
Incomplete documentation: Code blocks are not displayed in the extBase documentation

### ISSUE THREAD

**Issue by webmasterchiclana** [TYPO3-Documentation/t3SphinxThemeRtd#34]
Lot of code blocks are not displayed in the extBase documentation. Instead showing, **<remark>TODO: Enter Code</remark>**

**Example**: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/2-BasicPrinciples/1-Object-oriented%20Programming-in-PHP.html#interfaces

**Comment by marble** [comment]
Yes, it would be nice, somebody had entered those examples. Unfortunately nobody had done that until now. Pull requests are welcome.
