### ISSUE TITLE
Placeholder Example Type-Error

### ISSUE THREAD

**Issue by ReinhardtMedien** [TYPO3-Documentation/t3SphinxThemeRtd#37]
> In the above placeholder syntax, uid_local points to the related "sys_file" record and metadata points to the "sys_file_metata" of the related "sys_file" record. From there we take the content of the title field.

sys_file_meta**da**ta ... i think ;)

**Comment by marble** [comment]
Note: This is the issue tracker of the Theme! So I don't know to which actual TYPO3 manual this issue belongs. The theme is used on ALL of our pages.
