### ISSUE TITLE
f:form.checkbox - missing simple Example and description of required attribute value

### ISSUE THREAD

**Issue by Padina42** [TYPO3-Documentation/t3SphinxThemeRtd#38]
example 
Create a simple yes/no-Checkbox.
```
<label for="accept-rules">
     <span> You accept our rules</span>
     <f:form.checkbox property="acceptRules"
                      value="TRUE"
                      id="accept-rules"
     />
</label>
```
Shit. I havn't tested correctly. It don't work in that way. Ignore this message. How can I build a simple flag-checkabox? A description would help me.

**Comment by marble** [comment]
Please add your issues at the appropriate project. This one is for "theme"! issues only.
