### ISSUE TITLE
Markdown: code not rendered correctly

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3SphinxThemeRtd#39]
The example code on https://docs.typo3.org/typo3cms/extensions/flux/ is not rendered correctly.

It renders nicely on github: https://github.com/FluidTYPO3/flux/blob/development/README.md

![2017-02-15 docs typo3 org fluid](https://cloud.githubusercontent.com/assets/59036/22973915/1921b02c-f380-11e6-8eb5-d4fca5d593a1.png)

**Comment by cweiske** [comment]
The flux README uses the following markup to specify the language:

    ```xml
    <flux:form id="myform">
      <flux:field.input name="myField" label="My special field" />
    </flux:form>
    ```

**Comment by sypets** [comment]
In this case, I would suggest to convert the markdown Readme to reST. Restructured text code blocks will render nicely on Github and on the documentation server docs.typo3.org. Most of the TYPO3 documentation is written in reST.

See also: https://docs.typo3.org/typo3cms/HowToDocument/Appendix/SupportedFilenamesAndFormats.html

and 

https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/Codeblocks.html

You can use the tool `pandoc` to convert.

**Comment by sypets** [comment]
The source code snippets now look ok: https://docs.typo3.org/typo3cms/extensions/flux/stable/

I have also tested the following README.md:

    flux

    ```xml
    <flux:form id="myform">
      <flux:field.input name="myField" label="My special field" />
    </flux:form>
    ```


The result looks like this:

![flux](https://user-images.githubusercontent.com/13206455/59272051-6a988500-8c55-11e9-904c-227415e03893.png)


**Important**: If you want to test this locally, you need the [Docker image >= 2.0.0](https://github.com/t3docs/docker-render-documentation/issues/31#issuecomment-495983272). E.g., use the example commands as outlined here: https://github.com/t3docs/docker-render-documentation/issues/64

Thanks for bringing this up. 

If you can still reproduce problems, please reopen or create new issue and raise problem in Slack (#typo3-documentation).

BTW: The image above is really old rendering layout.

**Comment by cweiske** [comment]
No, the docs page does still not look nice: https://docs.typo3.org/typo3cms/extensions/flux/stable/

![2019-06-11 Auswahl_001](https://user-images.githubusercontent.com/59036/59273299-2490f080-8c58-11e9-98df-99ae043a57a0.png)

**Comment by sypets** [comment]
Can you do a reload? 

![flux](https://user-images.githubusercontent.com/13206455/59286301-c243ea00-8c6f-11e9-9bb9-035103b9c0b8.png)

**Comment by cweiske** [comment]
strange. I was sure I reloaded several times.
