### ISSUE TITLE
Document how to get rid of "Project Name 0.0.0" in extension documentation

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3SphinxThemeRtd#40]
Is there a way to get rid of the "Project Name 0.0.0" on the top left of https://docs.typo3.org/typo3cms/extensions/robots/ ? How?

google site search returns over 2000 results for that term

**Comment by marble** [comment]
Martin Bless [3:02 PM] 
@cweiske At the very moment: Put a Settings.yml file into EXT_ROBOTS/Documentation See chapter https://docs.typo3.org/typo3cms/extensions/sphinx/2.5.0/WritersManual/DocsTypo3Org/Index.html#title-copyright-and-version

Martin Bless [3:08 PM] 
At the moment the "old rendering chain" is at work. It may be necessary that you: (1) Copy README.rst to Documentation/Index.rst (2) Adjust the path to the figure in there, and (3) recommended: Replace the contents in the README.rst by a link to Documentation/Index.rst (for viewing at Github).
I'll soon start an "official manual¨ about "How to write TYPO3 documentation" to cover this kind of knowledge.
And I really expect things to become better - as soon as the server team gets the new machine ready for me and us. In the meantime: Keep on asking ;-))
