### ISSUE TITLE
Sitemap localization

### ISSUE THREAD

**Issue by emileblume** [TYPO3-Documentation/t3SphinxThemeRtd#42]
When using a sitemap (Sitemap Special Menus) in a different language it shows all non-translated pages despite the 'Hide the page if it is not translated' setting in the Behaviour setting of the page.
TYPO3 7.6.15/7.6.18

**Comment by marble** [comment]
Hello emileblume, not that this repository is about the THEME used to display TYPO3 documentation. I guess your're asking a "How to use TYPO3" question. This can be done at Slack or in the forum or the mailing lists.
