### ISSUE TITLE
How to get GP Parameter into a tx_Form field?

### ISSUE THREAD

**Issue by Sebra7** [TYPO3-Documentation/t3SphinxThemeRtd#43]
How is it Possible to Fill in a GP Parameter into a form field, who is given in the URL
In the Old Extension Mailform you where able to set in TS 
tt_content.mailform.20.data.insertData = 1
with this modification you where able to set a paramater to a Form Filed 
Kursdatum: | Kursdatum=input,40 | {GP:Kursdatum}

How does this works with the tx_Form extension?

The example below does not work. Where ist the thinking Failure?
10 = TEXTLINE
10 {
	type = text
	name = Kursdatum
        value ={GP:Kursdatum}
	label {
		value = Kursdatum
	}
}

Thank for any solution Sebastian

**Comment by marble** [comment]
Your question cannot be answered here as this repository is about display issues of the theme `t3SphinxThemeRtd` that's used for TYPO3 documentation. You may want to ask in the 'ext-form' channel in Slack though. That's where the experts are. https://typo3.slack.com/messages/C093RB4P9/ Get invite: https://forger.typo3.org/slack
