### ISSUE TITLE
Head Logo update & Default Color 

### ISSUE THREAD

**Issue by medhioub** [TYPO3-Documentation/t3SphinxThemeRtd#44]
Hello,
Is it possible to cutomize this theme by changing the color and the head logo ?

The idea is to add two new parameters in **config.py** under the section # t3SphinxThemeRtd : 

**1) Logo**
```
# The path to use a customized Head logo picture
# By default it will use Typo3 Documentation Logo
head_logo = /path/to/logo.png
```

**2) Main color**
```
# The main color that will be used 
# By default the color is orange
main_color = #00008b
```

With that update it will be perfect and the best RtD theme  ;)

**Comment by marble** [comment]
I'll keep this in mind and I'll have a look the next time I'm working on it. Yes, I understand: It would be great if we could create our own variants of this theme easily. But this hasn't priority, of course.

**Comment by marble** [comment]
1. The logo is configurable: https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/blob/master/t3SphinxThemeRtd/theme.conf So would we have to specify that somewhere in conf.py, or, in the context of TYPO3 projects, somewhere in the Settings-files (for example Settings.cfg). I must say though, that I don't know what exactly will happen - as long as you use the TYPO3 theme.

2. There are other themes for Sphinx around - you can use one of those for your own documentation.

3. The TYPO3 theme uses many colors, so you can't just change one value. Have a look at https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/blob/master/sass/_theme_variables.sass

HTH, hope this helps!

**Comment by KobaKhit** [comment]
Just save your logo under this name `./_static/img/typo3-documentation.png` in the sphinx root directory and your logo will show up.

**Comment by marble** [comment]
Thank you!
