### ISSUE TITLE
Add a button/link to hide the navigation bar

### ISSUE THREAD

**Issue by stmllr** [TYPO3-Documentation/t3SphinxThemeRtd#5]
Please add a button/link to hide the navigation bar on the left.
When zooming in on small screens, the nav gets too much space (and attention)

![typo3-doc](https://cloud.githubusercontent.com/assets/856735/10906400/81e1e630-8221-11e5-8a28-2f327a73c2ae.png)

Hiding the nav bar helps to focus on content.

**Comment by marble** [comment]
I'm not planning to make this happen due to complexity. On the other hand, pull requests for https://github.com/TYPO3-Documentation/t3SphinxThemeRtd are wellcome. Beware: That stuff is complex.
