### ISSUE TITLE
tsref: default values vs. titles

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/t3SphinxThemeRtd#52]
The titles of the properties are on the same line as the "default" values of the previous option.

See: https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Select/Index.html#recursive

![2017-09-04 auswahl_001](https://user-images.githubusercontent.com/59036/30025069-15cef1ba-9177-11e7-9cda-a1da523c3f82.png)

**Comment by marble** [comment]
'Default' usually has short content. So it has width:30% and floats left. Would look fine like like here for example: https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#cache-clearatmidnight

So, what needs to be done: Edit the content and place "Default" in front of "Description". Looking for a volunteer! Would you like to do that?

**Comment by marble** [comment]
See also https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/56

**Comment by marble** [comment]
Implement with v3.6.14
