### ISSUE TITLE
Link does not get rendered

### ISSUE THREAD

**Issue by Scopestyle** [TYPO3-Documentation/t3SphinxThemeRtd#54]
https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Uri/Image.html#properties

Learn more links get rendered in plain text, instead of HTML.

**Comment by marble** [comment]
Actually the renderer did exactly what was in your markup. I fixed the reST markup. 

About reStructuredText: 
- https://docs.typo3.org/typo3cms/drafts/github/T3DocumentationStarter/Public-Info-000/Knowledgebase/HowToDocument/reStructuredText/Index.html

- https://docs.typo3.org/typo3cms/drafts/github/T3DocumentationStarter/Public-Info-000/Knowledgebase/HowToDocument/Hyperlinks/Index.html#the-complete-anonymous-form

- http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets

Heads up - keep going! And thank you very much for contributing. The good thing about reST is: There is only ONE dialect. Learn it and use it for the rest of your life. Reload and enjoy https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Uri/Image.html#width
