### ISSUE TITLE
Configure dateFormat for posts list

### ISSUE THREAD

**Issue by AgenceGlanum** [TYPO3-Documentation/t3SphinxThemeRtd#63]
Hi,

I can't overload the default value for the date format of the posts list. 
I tried to insert the typoscript line "plugin.tx_blog.settings.list.posts.dateFormat = %Y.%m.%d" in:
- Setup of my blog template
- Constants of my blog template
- TSConfig of the root page of my blog
Even if the cache is empty, the value is always the default. (%d.%m.%Y)

Thanks for help,

![advans group typo3 cms 8 7 9](https://user-images.githubusercontent.com/14749410/35922536-1f8801e8-0c1e-11e8-8097-930e5f80c467.png)
![advans group typo3 cms 8 7 9_1](https://user-images.githubusercontent.com/14749410/35922538-1fa9b14e-0c1e-11e8-8bbd-d4f6865fb3a2.png)
![advans group typo3 cms 8 7 9_2](https://user-images.githubusercontent.com/14749410/35922539-1fcbde5e-0c1e-11e8-9856-5f7446cf334f.png)

**Comment by marble** [comment]
This repository deals with the theming (=appearance) of the documentation only. Please ask in the appropriate Slack channel https://typo3.slack.com/messages/C1XLMLRM1. Get a Slack invite at https://forger.typo3.com/slack You may still link to this issue https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/63 But please post follow ups somewhere else.
