### ISSUE TITLE
Add previous / next buttons to top as well as to bottom

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#66]
When paging through a manual, it would sometimes be convenient to not have to scroll down in order to get to the "next" (or previous) button.

Example: https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Sitemap/Index.html

Here, we've got a sitemap which I would like to skip while reading. Having to scroll down, makes reading tedious. 

If possible, add the buttons to the header in order to not make the page longer.

(I'm aware of the read-on-one-page and pdf version, but some people prefer the single page version).

**Comment by marble** [comment]
Did you try the keyboard shortcuts?
![grafik](https://user-images.githubusercontent.com/307057/42127667-3704265e-7c9d-11e8-9e1c-18f5c83385c0.png)

Accesskey+n for next, Accesskey+p for previous.
I once considered this as well, but didn't like the additional "visual noise". We could think of a less obstrusive appearence. But then we probably have the next question: Why does it look different at the top?

**Comment by sypets** [comment]
Thanks, the keyboard shortcuts work. The label pops up when you hover. I didn't realize this.

Having navigation controls at top and bottom may be a personal preference of mine. I understand you don't want to clutter up the page. I guess, one way would be to have several design solutions and let several people test them. A lot of work. 

Perhaps we should put this on ice for now?

**Comment by marble** [comment]
Done in development branch. Will come with the next version (>=v3.6.15)
