### ISSUE TITLE
Wrong migration information in deprecation note #80527

### ISSUE THREAD

**Issue by stoppeye** [TYPO3-Documentation/t3SphinxThemeRtd#73]
The deprecation notice lists a number of methods in ContentObjectRenderer that have been marked as deprecated and recommends to use MarkerBasedTemplateService instead. It claims that this class "contains equivalents to all methods that have been marked as deprecated with the same functionality and namings".

That's not true. There are no equivalent methods in MarkerBasedTemplateService for:

substituteMarkerArrayCached()
substituteMarkerInObject()
fillInMarkerArray()

**Comment by marble** [comment]
Note that this is the wrong repository for your ticket. This repository care about THE THEME only, that is, about HOW the docs are render. Please move the ticket to the repository of THE MANUAL where it belongs. You can find that repository by clicking on "Edit me on Github" at the top right, or, possibly, at the lower left "Related files".  Thank you for participating.
