### ISSUE TITLE
indexed search not indexing the alternative language pages

### ISSUE THREAD

**Issue by anujaunds** [TYPO3-Documentation/t3SphinxThemeRtd#79]
I have faced some problem with indexed_search in typo3 (8.7.10). It is only indexing the default language page. Currently i have selected three language on my website like English, German and Chinense. I already installed the crawl extension but faced same issue. Could you please let me the solution

**Comment by xperseguers** [comment]
This is the tracker for the theme project for *documentation*. Please open a ticket in the TYPO3 channel or ask for help on Slack (https://my.typo3.org/index.php?id=35)
