### ISSUE TITLE
Call to a member function getUploadedFiles() on null

### ISSUE THREAD

**Issue by momo9044** [TYPO3-Documentation/t3SphinxThemeRtd#80]

**Comment by DanielSiepmann** [comment]
@momo9044 can you provide some more information?

This repository is about the documentation theme. So this report is wrong here. Anyway we would like to help. So where did the error occur?

**Comment by sypets** [comment]
This looks rather like a programming error message. 

This is the Github repository for the Sphinx theme for rendering TYPO3 documentation, only issues that concern the rendering of the official TYPO3 documentation should go here.

Please do one of the following:
* If this is a problem in your own extension, you will have to solve it yourself. Here is where you can get help and support in general: https://typo3.org/help/
* If you have an issue about the official TYPO3 documentation, please go to the the Github repository for that manual and open an issue there. You can do that by clicking on the bottom left section of the rendered manual in the browser and then click on Issues:

![issues](https://user-images.githubusercontent.com/13206455/42409792-cf6e675a-81df-11e8-8126-baf87bee9dc4.png)


* If this is an extension bug, please find the extension and report the issue there, e.g. ke_search already has a similar issue: https://github.com/teaminmedias-pluswerk/ke_search/issues/158 . You can find the extension here: https://extensions.typo3.org/, find the extension and click on the green button "Found an issue? Get in contact!" (if it exists)

I am closing this issue now.
