### ISSUE TITLE
Restyle and restructure left navigation panel

### ISSUE THREAD

**Issue by foliengriller** [TYPO3-Documentation/t3SphinxThemeRtd#81]
Motivation:
The assignment of information and functional elements should be improved by the transformation and restructuring.

Changes:
- Information concerning the current document is summarized by the dark background.
- The orange background is used for grouping the parent level (documentation server)
- Information and selection of the version is assigned to the title of the document and only displayed if the document exists in several versions.
- The search is clearly recognizable by the magnifying glass icon which also acts as a submit button
- Distances and horizontal alignment improve the visibility of the structure

![screenshot-2018-6-23 templating tutorial basics templating tutorial basics 7 6 latest documentation 1](https://user-images.githubusercontent.com/24498435/41812316-0e2074d0-7721-11e8-96f0-3307b12f1e52.png)

**Comment by sypets** [comment]
I'm adding an image to visualize the current status and results for the ideas. 

I'm not changing anything of the original ideas, I used the screenshot above and compare it with the current rendering result.

![restructure_left_nav](https://user-images.githubusercontent.com/13206455/42412840-6e5e1098-8214-11e8-968d-16125fa0c570.png)

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
