### ISSUE TITLE
Find a way to make text more readable on wide screens (add maxwidth)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#83]
**Update**: 
* See also pending PR: #100
* See Project ["Improve Readability"](https://github.com/orgs/TYPO3-Documentation/projects/4) for all related issues and PR

# Problem

Currently, the docs use the entire width. This makes longer blocks of text not easy to read on wide screens. 

Example: https://docs.typo3.org/typo3cms/ExtbaseFluidBook/3-BlogExample/Index.html

![blog-example](https://user-images.githubusercontent.com/13206455/42409576-7b62db80-81dc-11e8-8354-91d3fc7d03fc.png)

# Solutions

## Solution 1: Limit the width of the main text section. 

Some examples:

* blogs often limit width of main text, e.g. https://www.copyblogger.com/scannable-content/
* readthedocs also does it: https://flowframework.readthedocs.io/en/latest/TheDefinitiveGuide/PartI/EssentialDesignPatterns.html

![flow](https://user-images.githubusercontent.com/13206455/42409567-538ef616-81dc-11e8-95c4-56e4fa7864ec.png)

**Comment by DanielSiepmann** [comment]
This should only be a setting as we forked the read the docs theme where this is already an setting.

**Comment by sypets** [comment]
There is another idea mentioned by @DavidBruchmann : 

Instead of limiting the width in general, split the text into multiple columns. 

See 

* W3C: [CSS Multi-column Layout](https://www.w3.org/TR/css-multicol-1/)
* browser support: https://caniuse.com/#feat=multicolumn

**Comment by sypets** [comment]
IMHO opinion, telling people to resize their browser is not a solution. IMHO, readability is an important criteria for the success of the docs. If you want people to use your website, you should make it usable (improve usability). If you want people to read your website, you should make it well readable (improve readability: not just the content, but also the formatting and everything else).

# Resources that support suggestion to limit width of content:

general readability (readability, line length, etc.):

* https://designshack.net/articles/mobile/the-importance-of-designing-for-readability/

line length

_“Anything from 45 to 75 characters is widely regarded as a satisfactory length of line for a single-column page set in a serifed text face in a text size. The 66-character line (counting both letters and spaces) is widely regarded as ideal. For multiple column work, a better average is 40 to 50 characters.”_

http://webtypography.net/2.1.2

_"for a single-column design should ideally be two to three alphabets long, around 40 to 80 characters. If the lines are too short then the text becomes disjointed, if they are too long the content loses rhythm as the reader searches for the start of each line. Many typographers consider the perfect measure to be 65 characters."_

https://spyrestudios.com/10-great-tips-for-improving-your-web-typography/

_"Line length matters. While people can read faster with longer text lines, they actually prefer shorter lines of texts of 45 to 72 characters. Make sure your lines wrap at this point."_

https://www.intechnic.com/blog/best-practices-to-improve-text-readability-for-optimal-user-experience/


fontsize:

https://ia.net/topics/100e2r


typography:

* https://tubikstudio.com/typography-in-ui-guide-for-beginners/
* https://spyrestudios.com/10-great-tips-for-improving-your-web-typography/



# Examples of documentation / blog articles that are well readable and restrict the width:


* readthedocs: https://flowframework.readthedocs.io/en/latest/
* developers.google.com: https://developers.google.com/web/tools/chrome-devtools/speed/get-started
* typo3worx: https://typo3worx.eu/2019/01/symfony-console-in-typo3/

**Comment by DavidBruchmann** [comment]
```
|------------------------- 66 ----------------------------------|  
“Anything from 45 to 75 characters is widely regarded as a satis-  
factory length of line for a single-column page set in a serifed  
text face in a text size. The 66-character line (counting both  
letters and spaces) is widely regarded as ideal. For multiple  
column work, a better average is 40 to 50 characters.”  

|-------------------------------- 80 -----------------------------------------|  
“Anything from 45 to 75 characters is widely regarded as a satisfactory length  
of line for a single-column page set in a serifed text face in a text size. The  
66-character line (counting both  letters and spaces) is widely regarded as  
ideal. For multiple column work, a better average is 40 to 50 characters.”  

|------------- 40 --------------------|  |------------- 40 --------------------|  
“Anything from 45 to 75 characters is    “Anything from 45 to 75 characters is  
widely regarded as a satisfactory        widely regarded as a satisfactory  
length of line for a single-column       length of line for a single-column  
page set in a serifed text face in a     page set in a serifed text face in a  
text size. The 66-character line         text size. The 66-character line  
(counting both  letters and spaces) is   (counting both  letters and spaces) is  
widely regarded as ideal. For multiple   widely regarded as ideal. For multiple  
column work, a better average is 40 to   column work, a better average is 40 to  
50 characters.”                          50 characters.”  

|---------------- 45 ----------------------|  |---------------- 45 ----------------------|  
“Anything from 45 to 75 characters is widely  “Anything from 45 to 75 characters is widely  
regarded as a satisfactory length of line     regarded as a satisfactory length of line  
for a single-column page set in a serifed     for a single-column page set in a serifed  
text face in a text size. The 66-character    text face in a text size. The 66-character  
line (counting both  letters and spaces) is   line (counting both  letters and spaces) is  
widely regarded as ideal. For multiple        widely regarded as ideal. For multiple  
column work, a better average is 40 to 50     column work, a better average is 40 to 50  
characters.”                                  characters.”  

|--------------------- 50 ----------------------|  |--------------------- 50 ----------------------|  
“Anything from 45 to 75 characters is widely       “Anything from 45 to 75 characters is widely  
regarded as a satisfactory length of line for a    regarded as a satisfactory length of line for a  
single-column page set in a serifed text face in   single-column page set in a serifed text face in  
a text size. The 66-character line (counting       a text size. The 66-character line (counting  
both  letters and spaces) is widely regarded as    both  letters and spaces) is widely regarded as  
ideal. For multiple column work, a better aver-    ideal. For multiple column work, a better aver-  
age is 40 to 50 characters.”                       age is 40 to 50 characters.”  
```

**Comment by DavidBruchmann** [comment]
A good example with different text-lengths is the main-page of https://www.nytimes.com/

**Comment by sypets** [comment]
**tip**: There are some browser extensions with which you can change styles for specific URLs. I have used [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne/related)

I have used this to test some changes in style. You can create a style for specific domain or docs.typo3.org. We could use this to test some style changes pretty easily without having to roll it out on a test server every time.

**Comment by sypets** [comment]
If the width is reduced too much, there are layout problems on the top "Edit me on GitHub", for example on https://docs.typo3.org/typo3cms/GettingStartedTutorial/OtherBackendModules/BackendLocalization/Index.html

![top](https://user-images.githubusercontent.com/13206455/55014750-d28ee600-4feb-11e9-9d9e-20aebdc76c87.png)

**Comment by sypets** [comment]
Current PR #100 should be tested and possibly further refined.

**Comment by marble** [comment]
① I consider this topic fixed in the next, upcoming version.

② The conflict was: Restricted text wide is good for reading, but can make the reading of wide code examples or wide tables really annoying. Or even impossible.

③ We now have a nice solution that fits both worlds in a nice and unobstructive way. It works like this. Usully text width will be limited:
![grafik](https://user-images.githubusercontent.com/307057/67618016-8c03a300-f7e9-11e9-9ccd-a47d7d6fccc4.png)

Hower, if you decide to make your window even wider, full screen view will kick in again:
![grafik](https://user-images.githubusercontent.com/307057/67618028-a473bd80-f7e9-11e9-8ea1-21be2a65bd6f.png)

This will happen automatically be means of a media query. And if the window is back to narrow the text width will be lmited again. I like that solution very much. Let's see how it works.

So I consider this issue "solved" for now.
