### ISSUE TITLE
Building t3SphinxThemeRtd fails with 404

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#85]
# Errors

##  1. URL for TYPO3_Share_Complete

Building t3SphinxThemeRtd according to [Readme](https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/blob/master/README.rst) fails on last step:

```
grunt
```

Error message:
```
bower TYPO3.styleguide#*                        progress received 3.6MB of 13.1MB downloaded, 28%
bower TYPO3_Share_Complete#*                       EHTTP Status code of 404
```

**./bower.json:**   
 "TYPO3_Share_Complete": 
```
"https://sourceforge.net/projects/typo3/files/TYPO3%20Resources/TYPO3_Share_Complete.ziphttps://sourceforge.net/projects/typo3/files/TYPO3%20Resources/TYPO3_Share_Complete.zip/download"
```
URL must be fixed.

## 2. fail to get font-source-sans-pro

```
bower TYPO3.styleguide#*                        progress received 2.8MB of 13.1MB downloaded, 21%
>> bower font-source-sans-pro-sass#~2.10.0          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/Arelav/font-source-sans-pro.git", exit code of #128 remote: Invalid username or password. fatal: Authentication failed for 'https://github.com/Arelav/font-source-sans-pro.git/'
>> Additional error details:
>> remote: Invalid username or password.
>> fatal: Authentication failed for 'https://github.com/Arelav/font-source-sans-pro.git/'
>> Exited with code: 1.

```

https://github.com/Arelav/font-source-sans-pro does not exist ...

**Comment by sypets** [comment]
As everything works with the docker image, I am closing this.

**Comment by sypets** [comment]
Don't know why I closed this. Seems it's still open.

**Comment by DanielSiepmann** [comment]
We worked on that during the sprint does it work using branch `feature/cleanup-frontend-stack` @sypets ?

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
