### ISSUE TITLE
a few questions about felogin

### ISSUE THREAD

**Issue by MS-Tech** [TYPO3-Documentation/t3SphinxThemeRtd#88]
Hello,

i would like to redirect to a page outside from the typo3. is this possible? I have an external PHP application. This application may only be called after a successful login. Is it possible to bind the login data from felogin to a session that I can use in my PHP application? I need the login information in my PHP application. I would like to use the felogin logout mechanism in my external PHP application. Is that possible?

Regards
MS-Tech

**Comment by sypets** [comment]
This place is for reporting issues about the rendering / theme of the official TYPO3 docs.

For help and support, please see: https://typo3.org/help/
