### ISSUE TITLE
Typo on Pitfalls.html

### ISSUE THREAD

**Issue by B-z-F** [TYPO3-Documentation/t3SphinxThemeRtd#91]
On page [Pitfalls.html](https://docs.typo3.org/typo3cms/extensions/ig_ldap_sso_auth/SSO/Pitfalls.html) is typo:
`Problem is that, although you set KrbMethodK5Passd off in your ...`
Should be:
`... KrbMethodK5Passwd ...`

**Comment by sypets** [comment]
The documentation for ig_ldap_sso_auth is maintained here : https://github.com/xperseguers/t3ext-ig_ldap_sso_auth

To find a doc repo, click on "Related links", and then on repository. I am moving and closing this issue. You can create a PR in the repo for the change.  

I created a new issue: https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/issues/41
