### ISSUE TITLE
Changed urls for links in contentinfo section (bottom)

### ISSUE THREAD

**Issue by jokumer** [TYPO3-Documentation/t3SphinxThemeRtd#92]
The content info section at the bottom of each document includes 2 links, which get 301/302 redirects

View page source
© Copyright since 1999 by the authors
Last rendered on ...
Built with Sphinx and t3SphinxThemeRtd. Report theme issues here.
Legal Info

1) Uri 'http://sphinx-doc.org/' has 302 redirect to 'http://www.sphinx-doc.org' which has a redirect to 'http://www.sphinx-doc.org/en/master/' and should be HTTPS 'https://www.sphinx-doc.org/en/master/'

2) Uri 'https://typo3.org/legal-info/' has 301 redirect to 'https://typo3.org/legal-notice/' and should be named 'Legal Notice'

I do not know, where to change it globaly...

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
