### ISSUE TITLE
Add homepage link to breadcrumb and change anchor text for start of manual

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#94]
I noticed, that it is not clear to everyone, you can click on "TYPO3 Documentation" on top left of page to get back to docs.typo3.org.

It might be helpful to add link to https://docs.typo3.org to beginning of breadcrumb. Currently, there is only "Docs" which gets you to beginning of manual, which is misleading. 

Also, instead of "Docs" the name of the manual or "Start" or something else might be better. 

Example: https://docs.typo3.org/typo3cms/GettingStartedTutorial/GeneralPrinciples/BackendAndFrontend/Index.html

![breadcrumb](https://user-images.githubusercontent.com/13206455/49326568-434d5680-f554-11e8-90bb-117e02f27195.png)

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/140
