### ISSUE TITLE
Ordering of version links is not correct?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3SphinxThemeRtd#99]
Is:

- 0.9.10
- 0.11.0
- 0.10.2
- 0.10.0

Should be (I think: latest first):

- 0.11.0
- 0.10.2
- 0.10.0
- 0.9.10

see https://docs.typo3.org/typo3cms/extensions/fp_newsletter/de-de/0.11.0/Configuration/, click "Related Links"

![versions](https://user-images.githubusercontent.com/13206455/52137353-a178e180-264a-11e9-86d0-802d462f5f12.png)

**Comment by sypets** [comment]
I have not often seen this and it should be less (since with move to new infrastructure, number of versions rendered decreased), so I am giving this a "low priority" label.

**Comment by DanielSiepmann** [comment]
This is for legacy extensions. We did not implement anything for legacy extensions as they will be removed in the future anyway. The listing only works on subpages by accident. I would not invest any time into this. If you like, the code is at Intercept and you can provide a PR.

**Comment by sypets** [comment]
Thanks. I am closing this. I think we have enough important stuff to do.
